spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:E:/h2/test
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /myapi/h2
      settings:
        web-allow-others: true